### ISSUE TITLE
TC_ISO_URL requires "www" in the URL

### ISSUE THREAD

**Issue by burtonis** [gpdm/tinycore-targetdisplaymode#1]
Running the build on Manjaro using podman, the script works perfectly with the following command:
`sudo podman run -it --rm -v `pwd`/output:/tmp/output -e TC_ISO_URL=http://www.tinycorelinux.net/13.x/x86/release/CorePlus-current.iso tcbuild`
however if I run it as
`sudo podman run -it --rm -v `pwd`/output:/tmp/output -e TC_ISO_URL="http://tinycorelinux.net/13.x/x86/release/CorePlus-current.iso" tcbuild`
I receive an error:
`Error: invalid ISO download source
/tmp/build/build.sh: line 27: exit status of last command: 1`

https://github.com/gpdm/tinycore-targetdisplaymode/blob/5fc1f962bf788a2031ce7987fe142dcd5d058328/files/build.sh#L27

might need to adjust the regex as follows so that it doesn't require the leading "www":
`^https?://w{0,3}.?tinycorelinux.net/[0-9]+.*/.*\.iso`

HTH!

**Comment by gpdm** [comment]
@burtonis 

I've changed regex validation in 7288ab0

please check again, thank you.

cheers,
-GP

**Comment by gpdm** [comment]
fixed as per 7288ab06c840fdd3b360ece9a0d6d02a2c8ce6bc
