### ISSUE TITLE
Working except for key commands

### ISSUE THREAD

**Issue by lenkaupert** [gpdm/tinycore-targetdisplaymode#13]
If I try to CTRL + ALT + F_ nothing happens. I can start up into TDM and use it but I can't toggle back or toggle it off and on so I can disconnect my computer and come back without restarting via the iMac's power button.

**Comment by gpdm** [comment]
If you use it with an Apple keyboard, you may need to also press the `Fn` key to unlock the F1-F12 keys.

So the key sequence to press woud be `CTRL + ALT + Fn + F1`
