### ISSUE TITLE
Error after EFI Boot

### ISSUE THREAD

**Issue by ArrudaFelipe** [gpdm/tinycore-targetdisplaymode#2]
After boot Tiny Core with EFI (Without gives the same error)

error: no such partition.
error: disk loop not found.
error: you need to load the kernel first

**Comment by gpdm** [comment]
Hi @ArrudaFelipe 

Did you prepare the USB stick as indicated on MacOS using the *diskutil* command, or did you use a different method?

First of all, I think it's the stick <2 GB or >2GB size topic.

Please check the partitioning scheme using *diskutil list* 
and follow the instructions at https://github.com/gpdm/tinycore-targetdisplaymode#initalizing-the-usb-drive-in-macos-terminal

Also check out for https://github.com/gpdm/tinycore-targetdisplaymode#i-got-boot-error-complaining-something-about-device--partition-not-found that you use the correct boot menu entry.

If this doesn't help, then please post me here some screen shot, and also the current partition scheme, which you can extract using the *diskutil list* command.

Thank you!

**Comment by ArrudaFelipe** [comment]
Yes, bud after that I've just copied the files inside /Users/deavi/tinycore-targetdisplaymode/output

In your video you've made the command:
scp -r sulogin@192.168.211.163:/tmp/tinycore-targetdisplaymode/output/*

I cant replicate the command because I cant understand it 

Is it the same as a simple copy?:
cp -R /Users/deavi/tinycore-targetdisplaymode/output/ /Volumes/TINYCORE

**Comment by gpdm** [comment]
@ArrudaFelipe 

The demonstration in the YT video is adapted to fit *my* particular build environment.

Hence, the `scp` command is the means I use to copy the files from my particular docker environment down to the USB thumb drive.

But this works for *my* environment, and is not intended for 1:1 replication.

YMMV depending on how you have setup your docker environment, and how you have configured docker.
This is things, to which I have no control about.

So if you have a local docker environment, that happens to write the output to */Users/deavi/tinycore-targetdisplaymode/output/* directly on your Mac, then I would assume, yes,

```
cp -R /Users/deavi/tinycore-targetdisplaymode/output/ /Volumes/TINYCORE
```

seems to be a possible way to copy the files over to your thumb drive.

However, as you didn't provide any further details, I'm purely left to guessworking here, whether the final file and directory structure on your USB thumb drive is correct, or not.

https://github.com/gpdm/tinycore-targetdisplaymode#run-the-build-inside-the-container provides an example, how the output directory should look like from a content perspective:

```
output/
output/boot
output/boot/grub
output/boot/grub/README.MD
output/boot/grub/grub.cfg
output/efi
output/efi/boot
output/efi/boot/bootX64.efi
output/boot-isos
output/boot-isos/Core-remastered.iso
```

So, if you've correctly copied everything over the your thumbdrive at */Volumes/TINYCORE/*, then the final structure must look exactly like this on the thumb drive:


```
/Volumes/TINYCORE/
/Volumes/TINYCORE/boot
/Volumes/TINYCORE/boot/grub
/Volumes/TINYCORE/boot/grub/README.MD
/Volumes/TINYCORE/boot/grub/grub.cfg
/Volumes/TINYCORE/efi
/Volumes/TINYCORE/efi/boot
/Volumes/TINYCORE/efi/boot/bootX64.efi
/Volumes/TINYCORE/boot-isos
/Volumes/TINYCORE/boot-isos/Core-remastered.iso
```


So step 1, please ensure your USB thumb drive has the content exactly as shown above.

If it doesn't, then please ensure it does.


And for step 2:

Please check again for https://github.com/gpdm/tinycore-targetdisplaymode#i-got-boot-error-complaining-something-about-device--partition-not-found

You will be presented with *two* (2) boot options, one reading

* Tiny Core Linux (USB <= 2.0 GiB, without EFI partition)
* Tiny Core Linux (USB > 2.0 GiB, with EFI partition)

Mind really about what's written here:

https://github.com/gpdm/tinycore-targetdisplaymode#initalizing-the-usb-drive-in-macos-terminal
and
https://github.com/gpdm/tinycore-targetdisplaymode#how-to-use

You have to choose yourself the one method, that matches your USB thumb drive's partition layout.

The error you seem to relate in the beginning in my opinion is exactly about using the *wrong* boot method.

Or, which is of course as well possible, you have an entirely different drive setup.
The latter could also influence the device numbering.

For my particular iMac, the drive IDs look like this:

 * sda == internal SATA HDD ( == hd2 in Grub )
 * sdb == USB smartCart reader ( == hd0 in Grub )
 * sdc == USB thumb drive ( == hd1 in Grub )


If this looks not the same for your, i.e. no CD-ROM/DVD, or no card reader, or a second built-in hard drive instead (maybe even a fusion drive?), then you may certainly need to tweak `/Volumes/TINYCORE/boot/grub/grub.cfg` yourself for the correct device-ID to be used.


In case your boot files on the USB key are OK, and you actually get the Grub prompt at the beginning,
you may try pressing 'C' to enter the command line.

You enter the grub CLI and get to see something like this:

```
grub>
```

Enter the `ls` command, like so, to get a device list similar to the one below

```
grub> ls
(memdisk) (hd0) (hd1) (hd1,gpt2) (hd1,gpt1) (hd2) (cd0)
```

You can easily walk through the individual entries, until you find the "TINYCORE" partition yourself, e.g. by doing this:

```
grub> ls (hd1,gpt2)
         Partition hd1,gpt2: Filesystem type fat - Label 'TINYCORE', UUID 9E2A-08E9 - Partition start at 205824KiB - Total size 3708928KiB
```

Let's assume, you find *TINYCORE* volume to be something else than *(hd1, gpt2)*, maybe for you, it's *(hd2,gpt2)*, then you need to adapt
https://github.com/gpdm/tinycore-targetdisplaymode/blob/main/files/grub/grub.cfg
accordingly to something like this:

```
menuentry "Tiny Core Linux (USB > 2.0 GiB, with EFI partition)" {
 loopback loop (hd2,gpt2)/boot-isos/Core-remastered.iso
 linux (loop)/boot/vmlinuz waitusb=10 iso=sdd2 nodhcp
 initrd (loop)/boot/core.gz
}
```

!Mind!

*loopback* command uses the grub ID, which is be *(hd1,gpt2)* in may case. It may be something else for you!

But fur the *linux* command, you need to point the *iso=* in this case to whatever matches your *(hdXYZ)* designation.

YMMV, but in my opinion, this is the only thing I can make reasonably sense of, that you need to adapt the device-IDs to match your particular iMac's drive configuration.

Hope this helps.
