### ISSUE TITLE
Does this work on an iMac 2017 as well?

### ISSUE THREAD

**Issue by kapabel** [gpdm/tinycore-targetdisplaymode#5]
Hello!
Does this work on an iMac 2017 as well? Apparently things have changed and new solutions are needed :(
Thanks!

**Comment by gpdm** [comment]
Hi @kapabel 

This link https://support.apple.com/en-us/HT204592 lists all iMac models, that support Target Display Mode.

In Short: 2009 to mid 2014 models.

This solution clearly doesn't work later year models, as they don't offer the TDM capability.

Best,
-GP
