### ISSUE TITLE
I followed the instructions, but end up at a tc@box:~$ prompt with no target display mode

### ISSUE THREAD

**Issue by codemonkey76** [gpdm/tinycore-targetdisplaymode#8]
I followed the instructions except could not get it to boot, had to modify the grub.cfg to use (hd5,gpt2), then it boots, but it boots to a terminal prompt target display mode not working, if i look in /usr/bin, there is no tdm_on, tdm_off or tdm_toggle files.

**Comment by gpdm** [comment]
Hi @codemonkey76 

This seems to be exactly the issue as described here: https://github.com/gpdm/tinycore-targetdisplaymode/blob/main/README.md#tdm-does-not-automatically-turn-on-on-boot

Please check also out https://github.com/gpdm/tinycore-targetdisplaymode/blob/main/README.md#device-identifiers-in-grubcfg
and the extra info in https://github.com/gpdm/tinycore-targetdisplaymode/blob/main/files/grub/README.md

If the device identifiers don't match up, and you had to adjust the `(hd5,gpt2)`, as you wrote, then you also need to adjust the `iso=sdc1` or `iso=sdc2` clauses to the correct identifier in `grub.cfg`.

You may want to check using the `dmesg | grep removable` to help you identify, which Linux device id was assigned to your USB key.

Here's an annotated example of what output I get:

```
sd 6:0:0:0 [sdb] Attached SCSI removable disk                        # built-in card reader
sd 7:0:0:0 [sdc] Attached SCSI removable disk                        # plugged-in USB thumb drive
```

Alternatively, do `dmesg | grep Direct-Access`, you may got something like this, which should also help in pointing at the correct device.

```
scsi 0:0:0:0 Direct-Access     ATA         Hitachi HDS72202 B23N PQ: 0 ANSI: 5
scsi 6:0:0:0 Direct-Access     APPLE       SD Card Reader   1.0  PQ: 0 ANSI: 0
scsi 7:0:0:0 Direct-Access     General     USB Flash Disk   1.0  PQ: 0 ANSI: 2
```

As you see from this example, for me the `7:0:0:0` matches up, hence for me it is `sdc`.
For you it may be `sde` or whatever the Linux kernel thought reasonable on your particular machine.

Cheers,
GP
